### ISSUE TITLE
Question about the spatial-wise RSC

### ISSUE THREAD

**Issue by YijinHuang** [DeLightCMU/RSC#3]
I am confused about the spatial-wise RSC. If you apply average pooling to z (final feature map) and feed in the fully connected layer, I believe that for any channel of z, all values in that channel will be the same. Therefore, after an average pooling along channel dimension, all cells in the 7*7 weighting matrix will have the same value too. So, how do you select top p percentage? Did I miss something? Thank you.

**Comment by Justinhzy** [comment]
Hi, you are right. For alexnet, z is diretly used to guide muting. For resnet, downsampled middle layer spatial gradients are used to guide muting for z. Now I have seperated the code for alexnet and resnet respectively. Hope it helps.

**Comment by YijinHuang** [comment]
> Hi, you are right. For alexnet, z is diretly used to guide muting. For resnet, downsampled middle layer spatial gradients are used to guide muting for z. Now I have seperated the code for alexnet and resnet respectively. Hope it helps.

Got it. Thank you.

**Comment by SirRob1997** [comment]
I think this is the issue I'm concerned about. According to the paper, in the Spatial-Wise RSC we perform average pooling across the channel domains. When we compute the average pooling spatially according to the ResNet architecture after masking out certain parts, this simply spreads feature values evenly across the image, both across spatial (from architecture) and channel (from RSC) dimensions.

However, the "fix" you propose doesn't really address this issue since interpolation is done one the [`spatial_mean`](https://github.com/DeLightCMU/RSC/blob/c46568709965ae5a1ea92e95ab6ae27cc190eb0d/models/resnet.py#L95) and not the relevant [`channel_mean`](https://github.com/DeLightCMU/RSC/blob/c46568709965ae5a1ea92e95ab6ae27cc190eb0d/models/resnet.py#L94). Am I missing something, or am I just confusing the inconsistent naming conventions here?
