### ISSUE TITLE
Confusing naming conventions

### ISSUE THREAD

**Issue by SirRob1997** [DeLightCMU/RSC#9]
I find myself confused about the naming conventions/comments and you should probably be more precise here. If I understood it correctly, the[ `channel_mean`](https://github.com/DeLightCMU/RSC/blob/c46568709965ae5a1ea92e95ab6ae27cc190eb0d/models/resnet.py#L94) is the mean used in Channel-Wise RSC and computes the mean across the spatial domain while the [`spatial_mean`](https://github.com/DeLightCMU/RSC/blob/c46568709965ae5a1ea92e95ab6ae27cc190eb0d/models/resnet.py#L95) is the mean used in Spatial-Wise RSC and computes the mean across the channel domain.

This is why we need `F.interpolate` in the Spatial-Wise RSC since it doesn't make sense for architectures with average pooling afterwards like mentioned here: #3. By the way: This isn't mentioned in the paper, what is the intuition behind that even?

**Comment by Justinhzy** [comment]
Hi, different convolutional layers should be able to locate discriminative spatial information consistently. The high-level convolutional layer tends to capture more semantic concepts while the low-level layer tends to capture more details. That's why spatial interpolation can be used in a convolutional network with average pooling.
